CREATE TABLE "pre_admissions" (
	"id" serial PRIMARY KEY NOT NULL,
	"application_level" varchar(255) NOT NULL,
	"academic_year" varchar(255),
	"semester" varchar(255),
	"grade_level" varchar(255),
	"first_choice" varchar(255),
	"second_choice" varchar(255),
	"family_name" varchar(255) NOT NULL,
	"given_name" varchar(255) NOT NULL,
	"middle_name" varchar(255),
	"gender" varchar(50) NOT NULL,
	"birth_date" varchar(50) NOT NULL,
	"age" varchar(10),
	"place_of_birth" text,
	"religion" varchar(255),
	"civil_status" varchar(50),
	"citizenship" varchar(100),
	"house_no" text,
	"province" text,
	"city_municipality" text,
	"barangay" text,
	"zip_code" varchar(20),
	"tel_no" varchar(50),
	"mobile_no" varchar(50),
	"email" varchar(255),
	"residence" varchar(255),
	"picture_url" text,
	"father_name" varchar(255),
	"father_address" text,
	"father_tel" varchar(50),
	"father_citizenship" varchar(100),
	"father_occupation" varchar(255),
	"father_office_address" text,
	"father_office_tel" varchar(50),
	"father_education" varchar(255),
	"father_last_school" text,
	"father_alumnus" varchar(10),
	"mother_name" varchar(255),
	"mother_address" text,
	"mother_tel" varchar(50),
	"mother_citizenship" varchar(100),
	"mother_occupation" varchar(255),
	"mother_office_address" text,
	"mother_office_tel" varchar(50),
	"mother_education" varchar(255),
	"mother_last_school" text,
	"mother_alumnus" varchar(10),
	"lrn_no" varchar(50),
	"last_school_attended" text,
	"school_address" text,
	"track" varchar(255),
	"strand" varchar(255),
	"school_year_attended" varchar(20),
	"date_of_graduation" varchar(50),
	"honors_awards" text,
	"is_transferee" varchar(10),
	"free_pre_admission" varchar(10),
	"previous_school" text,
	"stab_code" varchar(100),
	"preferred_schedule" varchar(255),
	"privacy_agreed" boolean DEFAULT false NOT NULL,
	"status" varchar(50) DEFAULT 'pending' NOT NULL,
	"submitted_at" timestamp DEFAULT now() NOT NULL
);
