CREATE TABLE IF NOT EXISTS "cumulative_records" (
	"id" serial PRIMARY KEY NOT NULL,
	"student_id" varchar(100),
	"academic_year" varchar(50),
	"department" varchar(100),
	"school_id" varchar(100),
	"full_name" varchar(255),
	"student_number" varchar(100),
	"address" text,
	"contact_number" varchar(50),
	"email" varchar(255),
	"birthday" varchar(50),
	"age" varchar(10),
	"nationality" varchar(100),
	"elem_school" varchar(255),
	"elem_year" varchar(50),
	"jhs_school" varchar(255),
	"jhs_year" varchar(50),
	"shs_school" varchar(255),
	"shs_year" varchar(50),
	"college_program" varchar(255),
	"college_year_level" varchar(50),
	"cor_upload" text,
	"enrollment_form_upload" text,
	"admission_record_upload" text,
	"report_card_upload" text,
	"tor_upload" text,
	"subject_load_upload" text,
	"psa_birth_cert_upload" text,
	"id_picture_upload" text,
	"school_id_upload" text,
	"good_moral_upload" text,
	"conduct_record_upload" text,
	"parent_name" varchar(255),
	"parent_relationship" varchar(100),
	"parent_contact" varchar(50),
	"emergency_person" varchar(255),
	"emergency_relationship" varchar(100),
	"emergency_contact" varchar(50),
	"status" varchar(50) DEFAULT 'draft',
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "verification_codes" (
	"id" serial PRIMARY KEY NOT NULL,
	"email" varchar(255) NOT NULL,
	"code" varchar(10) NOT NULL,
	"expires_at" timestamp NOT NULL,
	"used" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
