CREATE TABLE IF NOT EXISTS "student_needs_assessment" (
  "id" serial PRIMARY KEY NOT NULL,
  "student_id" varchar(100),
  "school_id" varchar(100),
  "academic_year" varchar(50),
  "department" varchar(100),
  "course_or_strand" varchar(255),
  "full_name" varchar(255),
  "email" varchar(255),
  "contact_number" varchar(50),
  "birthday" varchar(50),
  "age" varchar(10),
  "address" text,
  "academic_difficult_subjects" text,
  "academic_study_habits" text,
  "academic_learning_difficulties" text,
  "academic_concerns" text,
  "personal_problems" text,
  "personal_adjustment" text,
  "personal_family_concerns" text,
  "emotional_stress_level" varchar(20),
  "emotional_anxiety" text,
  "emotional_motivation" text,
  "emotional_self_confidence" text,
  "social_classmates" text,
  "social_friendships" text,
  "social_communication" text,
  "social_bullying" text,
  "financial_allowance" text,
  "financial_expenses" text,
  "financial_scholarship" text,
  "career_goal" text,
  "career_uncertainty" text,
  "career_skills" text,
  "health_medical" text,
  "health_physical_limitations" text,
  "support_counseling" boolean default false,
  "support_academic" boolean default false,
  "support_scholarship" boolean default false,
  "support_career" boolean default false,
  "support_other" text,
  "other_concerns" text,
  "status" varchar(50) default 'submitted',
  "created_at" timestamp default now() not null,
  "updated_at" timestamp default now() not null
);
